apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoponweb
  namespace: ci-02-webshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshoponweb
  template:
    metadata:
      labels:
        app: eshoponweb
    spec:
      containers:
      - name: eshoponweb
        image: ngdtrunguit/eshoponweb-webapp:1.0.5
        ports:
        - containerPort: 80
        env:  # Add your environment variables here
        - name: UseOnlyInMemoryDatabase
          value: "true"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "80"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        
---
apiVersion: v1
kind: Service
metadata:
  name: eshoponweb-service
  namespace: ci-02-webshop
spec:
  selector:
    app: eshoponweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer