apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo-01
  labels:
    app: ci-demo
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: ci-demo
  template:
    metadata:
      labels:
        app: ci-demo
    spec:
      containers:
      - name: ci-demo-container
        image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-demo-01-svc
spec:
  selector:
    app: ci-demo
  ports:
    - protocol: TCP
      port: 80  # Port to expose the service
      targetPort: 8000  # Port the container is exposing
  type: LoadBalancer  # Exposes the service externally. Use "ClusterIP" for internal services.